version: '3.9'

services:

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    working_dir: /var/www/laravel
    volumes:
      - ./auth-service:/var/www/laravel
    environment:
      DB_CONNECTION: mysql
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_DATABASE: auth_service
      DB_USERNAME: auth_user
      DB_PASSWORD: 1111
    depends_on:
      - auth-db

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_DATABASE: auth_service
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: 1111

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service

