services:

#nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./auth-service:/var/www/laravel
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - auth-service
    ports:
      - "8080:80"
    networks:
      - app_network

#auth-service
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    working_dir: /var/www/laravel
    volumes:
      - ./auth-service:/var/www/laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_DATABASE: auth_service
      DB_USERNAME: auth_user
      DB_PASSWORD: 1111
    depends_on:
      - auth-db
    networks:
      - app_network

  auth-db:
    image: postgres:13
    container_name: auth-db
    environment:
      PGPASSWORD: 1111
      POSTGRES_DB: auth_service
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: 1111
    volumes:
      - pg-data-auth:/var/lib/postgresql/data
    networks:
      - app_network
      
#user-service
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    working_dir: /var/www/laravel
    volumes:
      - ./user-service:/var/www/laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: user-db
      DB_PORT: 5432
      DB_DATABASE: user_service
      DB_USERNAME: user_user
      DB_PASSWORD: 1111
    depends_on:
      - user-db
    networks:
      - app_network

  user-db:
    image: postgres:13
    container_name: user-db
    environment:
      PGPASSWORD: 1111
      POSTGRES_DB: user_service
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: 1111
    volumes:
      - pg-data-user:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pg-data-auth:
    driver: local
  pg-data-user:
    driver: local

networks:
  app_network:
    driver: bridge